class SupplyItem:
    """Represents single medical supply item in registry."""
    def __init__(self, name, category, quantity):
        self.name = name
        self.category = category
        self.quantity = int(quantity)

    def __str__(self):
        return f"{self.name} ({self.category}): {self.quantity} units"


class Inventory:
    """Manages storage and logic for all medical supplies."""
    def __init__(self):
        # dictionary used to store items by name for easy access
        self.supplies_dict = {}

    def add_new_item(self, name, category, quantity):
        """Creates new supply object and adds it to our records."""
        if name not in self.supplies_dict:
            new_item = SupplyItem(name, category, quantity)
            self.supplies_dict[name] = new_item
            return True
        return False

    def update_quantity(self, name, amount):
        """Updates stock level of existing item."""
        if name in self.supplies_dict:
            self.supplies_dict[name].quantity += int(amount)
            return True
        return False

    def get_all_items(self):
        """Returns list of all current items."""
        return list(self.supplies_dict.values())


class StockReport:
    """Generates formatted reports based on inventory data."""
    def __init__(self, inventory_list):
        # takes list generated by the Inventory class
        self.items = inventory_list

    def generate_summary(self):
        """makes clean text-based list of current stock levels."""
        summary = []
        for item in self.items:
            line = f"STOCK ALERT: {item.name} | Category: {item.category} | Current Qty: {item.quantity}"
            summary.append(line)
        return summary